# YAML configuration for creating problem tickets in Jira
jira:
  base_url: "https://rb-tracker.bosch.com/tracker08-q/"
  create_problem_ticket:
    relates_to:
      branch_key_pattern: "[A-Z]+-[0-9]+"  # Extracts the Jira key from the branch name
  additional_fields:
    reporter: "{{commit_author}}"
    approver: "{{commit_author}}"
    due_date: "{{today + 6 weeks}}"
    cf[26728]: "Medium"
    cf[26726]: "Project Internal"
    cf[31220]: "No"
    cf[33921]: "Quality Activity"
    description_from_finding: true