name: QA PR Report

on:
  pull_request:

jobs:
  qa-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate QA Report
        run: python qa_to_html.py

      - name: Read JSON
        id: qa
        run: |
          QUESTIONS=$(jq '[.modules[].questions] | add' docs/qa_summary.json)
          OPEN=$(jq '[.modules[].open] | add' docs/qa_summary.json)
          COVERAGE=$((100 - OPEN * 100 / QUESTIONS))

          echo "questions=$QUESTIONS" >> $GITHUB_OUTPUT
          echo "open=$OPEN" >> $GITHUB_OUTPUT
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const questions = "${{ steps.qa.outputs.questions }}"
            const open = "${{ steps.qa.outputs.open }}"
            const coverage = "${{ steps.qa.outputs.coverage }}"

            const body = `
            ## QA Dashboard Result

            Questions: ${questions}
            Open Evidences: ${open}
            Coverage: ${coverage}%

            Dashboard:
            https://erikskroblien.github.io/test_github_quality_gate/qa_summary.html
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })